
app:
  image: $IMAGE_NAME
  ports:
    - 8443
  volumes:
    - ../logs:/mnt/logs
    - ../test:/app/test
    - $HOST_ROOT_MOUNT:$CONTAINER_ROOT_MOUNT
  working_dir: /app
  environment:
    - TEST=true
  links:
    - postgres:postgres
postgres:
  image: postgres
  ports:
    - 5432
  environment:
    - DEBUG=true
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
build:
  image: nodesource/centos7:latest
  working_dir: /build
  volumes:
    - ..:/build